version: 2
updates:
  # API (Rails) dependencies
  - package-ecosystem: bundler
    directory: "/api"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  # Frontend (Next.js) dependencies
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
